//Copyright 2021 ZeroOne\\

---You may not Change the Command Variables without the "M", do only Change this if you are changing the Source Code too, otherwise it will not work!---

Command1: cm1
Command1M: Test1
Command2: cm2
Command2M: Test2
Command3: cm3
Command3M: Test3
Command4: cm4
Command4M: Test4
Command5: cm5
Command5M: Test5
