//Copyright 2021 ZeroOne\\
name: Commandermessager
version: 1.0
main: com.felix.commander.commander.Commander
api-version: 1.16
author: ZeroOne
commands:
  cm1:
    description: Command 1
  cm2:
    description: Command 2
  cm3:
    description: Command 3
  cm4:
    description: Command 4
  cm5:
    description: Command 5

